package com.simpfi.object;

import java.util.Arrays;
import java.util.List;

import com.simpfi.util.Point;

import de.tudresden.sumo.util.SumoCommand;

/**
 * Creates Lane class (may includes {@link de.tudresden.sumo.cmd.Lane} in the
 * future).
 */
public class Lane {

	/** The lane id. */
	private String laneId;

	/** The lane shape. */
	private Point[] shape;

	/** The size of the lane shape. */
	private int shapeSize;

	/**
	 * Instantiates a new lane.
	 *
	 * @param laneId the lane id
	 * @param shape  the shape
	 */
	public Lane(String laneId, Point[] shape) {
		this.laneId = laneId;
		this.shape = shape;
		this.shapeSize = this.shape.length;
	}

	/**
	 * Instantiates a new lane.
	 *
	 * @param laneId the lane id
	 */
	public Lane(String laneId) {
		this.laneId = laneId;
	}

	/**
	 * Returns the lane id.
	 *
	 * @return the lane id
	 */
	public String getLaneId() {
		return laneId;
	}

	/**
	 * Returns the shape.
	 *
	 * @return the shape
	 */
	public Point[] getShape() {
		return shape;
	}

	/**
	 * Returns the shape size.
	 *
	 * @return the shape size
	 */
	public int getShapeSize() {
		return shapeSize;
	}

	/**
	 * Search for a lane in a list of edges. This assumes that all lanes are
	 * formatted in a way that we can know in which edge a lane is from. This is
	 * possible because the lanes are automatically generated by SUMO NetEdit.
	 *
	 * @param id    the id of the lane to be searched for
	 * @param edges the list of edges
	 * @return the found lane or {@code null} if not found
	 */
	public static Lane searchForLane(String id, List<Edge> edges) {
		String edgeId = id.split("_")[0];
		Edge edge = Edge.searchForEdge(edgeId, edges);
		Lane[] lanes = edge.getLanes();
		for (int i = 0; i < lanes.length; i++) {
			if (lanes[i].getLaneId().equals(id)) {
				return lanes[i];
			}
		}
		return null;
	}
	

	/**
	 * Overrides the built-in method toString() to provide a human-readable
	 * representation of Lane.
	 *
	 * @return the representation of Lane
	 */
	@Override
	public String toString() {
		return "Lane [laneId=" + laneId + ", shape=" + Arrays.toString(shape) + "]";
	}

}
