package com.simpfi.object;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.util.Arrays;
import java.util.List;

import com.simpfi.config.Settings;
import com.simpfi.util.GraphicsSettings;
import com.simpfi.util.Point;

/**
 * Creates Lane class (may includes {@link de.tudresden.sumo.cmd.Lane} in the
 * future).
 */
public class Lane extends SumoObject implements Drawable {

	/** The lane shape. */
	private Point[] shape;

	/** The size of the lane shape. */
	private int shapeSize;

	/**
	 * Instantiates a new lane.
	 *
	 * @param id    the lane id
	 * @param shape the shape
	 */
	public Lane(String id, Point[] shape) {
		this.id = id;
		this.shape = shape;
		this.shapeSize = this.shape.length;
	}

	/**
	 * Instantiates a new lane.
	 *
	 * @param id the lane id
	 */
	public Lane(String id) {
		this.id = id;
	}

	/**
	 * Returns the shape.
	 *
	 * @return the shape
	 */
	public Point[] getShape() {
		return shape;
	}

	/**
	 * Returns the shape size.
	 *
	 * @return the shape size
	 */
	public int getShapeSize() {
		return shapeSize;
	}

	/**
	 * Search for a lane in a list of edges. This assumes that all lanes are
	 * formatted in a way that we can know in which edge a lane is from. This is
	 * possible because the lanes are automatically generated by SUMO NetEdit.
	 *
	 * @param id    the id of the lane to be searched for
	 * @param edges the list of edges
	 * @return the found lane or {@code null} if not found
	 */
	public static Lane searchForLane(String id, List<Edge> edges) {
		String edgeId = id.split("_")[0];
		Edge edge = Edge.searchForEdge(edgeId, edges);
		Lane[] lanes = edge.getLanes();
		for (int i = 0; i < lanes.length; i++) {
			if (lanes[i].getId().equals(id)) {
				return lanes[i];
			}
		}
		return null;
	}

	/**
	 * Overrides the built-in method toString() to provide a human-readable
	 * representation of Lane.
	 *
	 * @return the representation of Lane
	 */
	@Override
	public String toString() {
		return "Lane [laneId=" + id + ", shape=" + Arrays.toString(shape) + "]";
	}

	/**
	 * Draws a {@link Lane} on the map
	 *
	 * @param g the {@link Graphics2D}
	 * @param l the lane
	 * @param c the color
	 */
	@Override
	public void draw(Graphics2D g, Color c, SimulationSnapshot snapshot) {
		GraphicsSettings oldSettings = GraphicsSettings.saveCurrentGraphicsSettings(g);

		Point[] shape = getShape();
		int size = getShapeSize();

		if (size < 2) {
			return;
		}

		int[] xPoints = new int[size];
		int[] yPoints = new int[size];

		for (int i = 0; i < size; i++) {
			Point p = shape[i].fromWorldToMap();
			xPoints[i] = (int) p.getX();
			yPoints[i] = (int) p.getY();
		}

		float lineThickness = (float) (Settings.config.LANE_STROKE_SIZE * Settings.config.SCALE);

		g.setColor(c);
		g.setStroke(new BasicStroke(lineThickness, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));

		g.drawPolyline(xPoints, yPoints, size);

		GraphicsSettings.loadGraphicsSettings(g, oldSettings);
	}

}
